apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-lb-srv
spec:
  selector:
    app: platformnpservice-lb
  ports:
    - port: 8765
      targetPort: 80
      nodePort: 30180
  type: LoadBalancer